In [1]:
import cv2
from matplotlib import pyplot as plt
im = cv2.imread("images/big.jpg")
plt.imshow(im)
print(im)

[[[ 29  78 110]
  [ 29  78 110]
  [ 29  78 110]
  ...
  [ 51 103 143]
  [ 50 102 142]
  [ 49 101 141]]

 [[ 29  78 110]
  [ 29  78 110]
  [ 30  79 111]
  ...
  [ 51 103 143]
  [ 50 102 142]
  [ 50 102 142]]

 [[ 30  79 111]
  [ 30  79 111]
  [ 30  79 111]
  ...
  [ 51 103 143]
  [ 50 102 142]
  [ 50 102 142]]

 ...

 [[ 16  30  42]
  [ 16  30  42]
  [ 16  30  42]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 15  29  41]
  [ 15  29  41]
  [ 15  29  41]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 15  29  41]
  [ 15  29  41]
  [ 17  29  41]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [2]:
#получение размера изображения

size = im.shape[0]*im.shape[1]
print("Size = {}".format(size))

Size = 187500


In [30]:
import numpy as np

#Средние значения по каналам
meanChanel1 = im[:,:,0].mean()
meanChanel2 = im[:,:,1].mean()
meanChanel3 = im[:,:,2].mean()

print("Среднее значение в 3-ем канале = {}".format(meanChanel3))


Среднее значение в 3-ем канале = 128.69120533333333


In [28]:
#среднее квадратическое отклонение по каналам
std1 = im[:,:,0].std()
std2 = im[:,:,1].std()
std3 = im[:,:,2].std()

std1

38.29606241503853

In [5]:
#поменять каналы местами
revIm = im[:,:,::-1]
print(revIm[0,345,0])

192


In [6]:
np.random.seed(7964)
A = np.random.randint(0,8,size=(500,500))

In [42]:
A==7
(((A==7).sum(axis=(0)))>0).sum()

500

In [8]:
#сумма индексов ячеек, значени которых меньше 4
indArr1 = (A<4).nonzero()
print(indArr1)
res1 = indArr1[0].sum() + indArr1[1].sum()
print(res1)

(array([  0,   0,   0, ..., 499, 499, 499]), array([  2,   5,   6, ..., 493, 495, 499]))
62383552


In [9]:
#сумма индексов ячеек, значени которых меньше 4 и больше 2

indArr2 = ((A<4)*(A>2)).nonzero()
res2 = indArr2[0].sum() + indArr2[1].sum()
print(res2)

15541519


In [10]:
#сумма всех значений по индексам из предыдущего задания
print(A[indArr2].sum())

93516


## Axis in numpy
![title](images/axes.jpg)

In [24]:
#максимальное значение в каждом столбце массива
A.max(axis=0).sum()

3500

In [12]:
x = np.arange(1,501,1)

In [25]:
#скалярное произведение
A.dot(x).sum()

218833635

In [14]:
np.random.seed(33)
w = np.random.randint(0,8,size=(5,500))

In [26]:
#массив A на массиц w транспонированный
(A@w.T).sum()

15215957

In [27]:
#массив A на массиц w поэлементно
c = np.tile(w,(100,1))
(A*c).sum()

3045726

In [168]:
# arr3d = [[[1,2,3],[1,2,3],[1,2,3]],
#        [[1,2,3],[1,2,3],[1,2,3]],
#        [[1,2,3],[1,2,3],[1,2,3]]]
# nparr3d = np.array(arr3d)
# arr2d = [[1,2,3],
#        [1,2,3],
#        [1,2,3]]
# nparr2d = np.array(arr2d)

# nparr2d.max(axis=0)

# x = np.array([[1,2,3],
#      [1,2,3],
#      [1,2,3]])
# y = np.array([1,2,3])
# print(x*x)

[[1 4 9]
 [1 4 9]
 [1 4 9]]
